[project]
name = "python_uv_ruff_template"
version = "0.1.0"
description = "Simple template for python project with uv and ruff"
readme = "README.md"
authors = [{ name = "Petr Malafeev", email = "malafeevpa@yandex.ru" }]

requires-python = "==3.14.*"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.8",
]

[project.urls]
repository = "https://github.com/Pythonusus/python_uv_ruff_template.git"

[tool.ruff]
line-length = 80
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "*.pyc",
    "*.egg-info",
    "build",
    "dist",
]

[tool.ruff.lint]
preview = true
select = ["A", "E", "F", "W", "I", "C90", "RET", "Q"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"] # ignore unused imports for __init__.py

[tool.ruff.format]
quote-style = "preserve"

[tool.pytest.ini_options]
python_files = ["tests.py", "test_*.py", "*_tests.py"]

[tool.coverage.run]
data_file = "coverage/.coverage"
source = ["app"]
omit = [
    "*/venv/*",
    "*/__init__.py",
    "*/tests/*",
    "*/tests.py",
    "test_*.py",
    "*_tests.py",
]

[tool.coverage.html]
directory = "coverage/htmlcov"

[tool.coverage.xml]
output = "coverage/coverage.xml"
